// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtc_p9_zKfPW_wICyp5qWFlqYSLCR0yYY',
    appId: '1:800541292018:web:b384c72504d28e033d676b',
    messagingSenderId: '800541292018',
    projectId: 'wevo-22275',
    authDomain: 'wevo-22275.firebaseapp.com',
    storageBucket: 'wevo-22275.firebasestorage.app',
    measurementId: 'G-TG0ZCQB0Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2KHPZ7WvnIqDC8Phi5flCCmRuQmqavkE',
    appId: '1:800541292018:android:405e5068a02134433d676b',
    messagingSenderId: '800541292018',
    projectId: 'wevo-22275',
    storageBucket: 'wevo-22275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSdJaj2FGny-M7zCIclOPqsLG18exh5F0',
    appId: '1:800541292018:ios:5601ea3c3152d2ac3d676b',
    messagingSenderId: '800541292018',
    projectId: 'wevo-22275',
    storageBucket: 'wevo-22275.firebasestorage.app',
    iosBundleId: 'com.nemis.nemisApp',
  );
}
